export const placeholderbookings = [

    {
        bookingId: 1,
        showtimeId: 1,
        row: 1,
        col: 1,
        price: 75,
        bookingNumber: 1001,
        userId: null,
        bookingDatetime: null,
        ticketType: 1,
    },
    {
        bookingId: 2,
        showtimeId: 1,
        row: 1,
        col: 2,
        price: 75,
        bookingNumber: 1001,
        userId: null,
        bookingDatetime: null,
        ticketType: 1,
    },
    {
        bookingId: 3,
        showtimeId: 1,
        row: 1,
        col: 3,
        price: 75,
        bookingNumber: 1001,
        userId: null,
        bookingDatetime: null,
        ticketType: 1,
    },
    {
        bookingId: 4,
        showtimeId: 1,
        row: 2,
        col: 1,
        price: 75,
        bookingNumber: 1002,
        userId: null,
        bookingDatetime: null,
        ticketType: 1,
    },
    {
        bookingId: 5,
        showtimeId: 2,
        row: 3,
        col: 5,
        price: 75,
        bookingNumber: 1003,
        userId: null,
        bookingDatetime: null,
        ticketType: 1,
    },
    {
        bookingId: 6,
        showtimeId: 2,
        row: 3,
        col: 6,
        price: 75,
        bookingNumber: 1003,
        userId: null,
        bookingDatetime: null,
        ticketType: 1,
    },


]